<a href="https://colab.research.google.com/github/gv1010/ml-coding/blob/main/pytorch/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.2.1+cu121'

In [10]:
scalar = torch.tensor([10, 10])
scalar.size(), scalar.ndim

(torch.Size([2]), 1)

In [13]:
matrix = torch.tensor([[1,2], [3,4]])
matrix.ndim, matrix.shape

(2, torch.Size([2, 2]))

In [15]:
tensor_ = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor_.shape, tensor_.ndim

(torch.Size([1, 3, 3]), 3)

# Random tensor

In [17]:
random_tensor = torch.rand(size=(2,3))
random_tensor, random_tensor.shape, random_tensor.dtype

(tensor([[0.0864, 0.7972, 0.7644],
         [0.4993, 0.7410, 0.8320]]),
 torch.Size([2, 3]),
 torch.float32)

In [20]:
random_tensor = torch.rand(size=(12,12,3))
random_tensor.ndim, random_tensor.shape, random_tensor.dtype

(3, torch.Size([12, 12, 3]), torch.float32)

In [29]:
zeros = torch.zeros(size=(5,4), dtype = torch.int8)
zeros.dtype, zeros

(torch.int8,
 tensor([[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]], dtype=torch.int8))

In [31]:
range_tensor = torch.arange(start=-1, end = 10, step=0.5)
range_tensor

tensor([-1.0000, -0.5000,  0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,
         3.0000,  3.5000,  4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,
         7.0000,  7.5000,  8.0000,  8.5000,  9.0000,  9.5000])

In [32]:
alike_matrix = torch.zeros_like(input = zeros)
alike_matrix

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int8)

# Tensor Manipulation

In [39]:
((zeros + 10)*2)%3

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]], dtype=torch.int8)

In [51]:
# zeros = zeros

In [49]:
mat = (zeros + 5.5)*2
mat

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])

In [50]:
mat * mat # int8 limits to (-128, 127)

tensor([[121., 121., 121., 121.],
        [121., 121., 121., 121.],
        [121., 121., 121., 121.],
        [121., 121., 121., 121.],
        [121., 121., 121., 121.]])

In [53]:
mat @ mat.T

tensor([[484., 484., 484., 484., 484.],
        [484., 484., 484., 484., 484.],
        [484., 484., 484., 484., 484.],
        [484., 484., 484., 484., 484.],
        [484., 484., 484., 484., 484.]])

In [56]:
mat.T.matmul(mat)

tensor([[605., 605., 605., 605.],
        [605., 605., 605., 605.],
        [605., 605., 605., 605.],
        [605., 605., 605., 605.]])

In [70]:
a = torch.ones(size=(3,4), dtype = torch.float32)
b = torch.rand(size=(4,3), dtype = torch.float32)

a @ b

tensor([[2.5524, 1.8049, 2.2249],
        [2.5524, 1.8049, 2.2249],
        [2.5524, 1.8049, 2.2249]])

In [71]:
torch.matmul(a, b)

tensor([[2.5524, 1.8049, 2.2249],
        [2.5524, 1.8049, 2.2249],
        [2.5524, 1.8049, 2.2249]])

In [79]:
a = torch.rand(size=(1,3,4))
a, a.shape

(tensor([[[0.6458, 0.5091, 0.9749, 0.5967],
          [0.6297, 0.6302, 0.7949, 0.9297],
          [0.6699, 0.0014, 0.3978, 0.2517]]]),
 torch.Size([1, 3, 4]))

In [80]:
at = a.transpose(0,2)
at, at.shape

(tensor([[[0.6458],
          [0.6297],
          [0.6699]],
 
         [[0.5091],
          [0.6302],
          [0.0014]],
 
         [[0.9749],
          [0.7949],
          [0.3978]],
 
         [[0.5967],
          [0.9297],
          [0.2517]]]),
 torch.Size([4, 3, 1]))

In [90]:
a = torch.arange(0,10,1)
a = a.type(torch.float32)

a, a.dtype, a.mean()

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.float32,
 tensor(4.5000))

In [88]:
a.type(torch.float32).mean()

tensor(4.5000)

In [94]:
torch.mean(torch.tensor([1,2,3], dtype=torch.float32))

tensor(2.)

In [96]:
a = torch.rand(size = (1,2), dtype=None)
a, a.dtype

(tensor([[0.9358, 0.5089]]), torch.float32)

In [99]:
mat.view(1, 20)

tensor([[11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.,
         11., 11., 11., 11., 11., 11.]])

In [102]:
a =torch.arange(0,12,1)
a.reshape(2,2,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [104]:
a = torch.rand(size = (2,3), dtype=None)
b = a.view(1, 6)
b, a

(tensor([[0.6358, 0.5912, 0.1711, 0.5940, 0.8551, 0.4191]]),
 tensor([[0.6358, 0.5912, 0.1711],
         [0.5940, 0.8551, 0.4191]]))

In [108]:
b[0,:] = 100
b, a # change in view, changes the original tensor

(tensor([[100., 100., 100., 100., 100., 100.]]),
 tensor([[100., 100., 100.],
         [100., 100., 100.]]))

In [111]:
a.shape

torch.Size([2, 3])

In [120]:
b = torch.tensor([[1,2,3],[4,5,6]])
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [121]:
torch.stack([b, b, b], dim=1), torch.stack([b,b,b], dim=1).shape

(tensor([[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],
 
         [[4, 5, 6],
          [4, 5, 6],
          [4, 5, 6]]]),
 torch.Size([2, 3, 3]))

In [122]:
torch.stack([b, b, b], dim=0), torch.stack([b,b,b], dim=0).shape

(tensor([[[1, 2, 3],
          [4, 5, 6]],
 
         [[1, 2, 3],
          [4, 5, 6]],
 
         [[1, 2, 3],
          [4, 5, 6]]]),
 torch.Size([3, 2, 3]))

In [124]:
torch.stack([b, b, b], dim=-1), torch.stack([b,b,b], dim=-1).shape

(tensor([[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]],
 
         [[4, 4, 4],
          [5, 5, 5],
          [6, 6, 6]]]),
 torch.Size([2, 3, 3]))

In [134]:
x = torch.rand(size=(1,4,3))
x, x.permute(1,2,0)

(tensor([[[0.1126, 0.3160, 0.3257],
          [0.1301, 0.7383, 0.5945],
          [0.1646, 0.7849, 0.3657],
          [0.3548, 0.3062, 0.8152]]]),
 tensor([[[0.1126],
          [0.3160],
          [0.3257]],
 
         [[0.1301],
          [0.7383],
          [0.5945]],
 
         [[0.1646],
          [0.7849],
          [0.3657]],
 
         [[0.3548],
          [0.3062],
          [0.8152]]]))

In [135]:
y = x.permute(1,0,2)
y[:1,0]=4
y, y.shape #

(tensor([[[4.0000, 4.0000, 4.0000]],
 
         [[0.1301, 0.7383, 0.5945]],
 
         [[0.1646, 0.7849, 0.3657]],
 
         [[0.3548, 0.3062, 0.8152]]]),
 torch.Size([4, 1, 3]))

In [136]:
x

tensor([[[4.0000, 4.0000, 4.0000],
         [0.1301, 0.7383, 0.5945],
         [0.1646, 0.7849, 0.3657],
         [0.3548, 0.3062, 0.8152]]])

In [137]:
# has the same effect as view, changes the values

In [139]:
a.numpy() # default dtype=float32, in numpy

array([[100., 100., 100.],
       [100., 100., 100.]], dtype=float32)

In [1]:
# numpy does not work on gpu
import torch

In [5]:
torch.cuda.device_count()

1

In [15]:
torch.cuda.manual_seed(seed=1)

In [19]:
torch.manual_seed(seed=1)
a = torch.rand(size=(2,3), device = "cuda")
a

tensor([[0.8903, 0.0275, 0.9031],
        [0.5386, 0.7312, 0.9047]], device='cuda:0')

In [20]:
torch.rand(size=(2,3))

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [21]:
torch.cuda.random.manual_seed(seed=1) # this is must to have else it give different values
torch.rand(size=(2,3), device = "cuda")

tensor([[0.8903, 0.0275, 0.9031],
        [0.5386, 0.7312, 0.9047]], device='cuda:0')