In [3]:
# !pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu -t /home/gv/work/ml/lib/python3.11/site-packages

In [1]:
import torch
import numpy as np
from pprint import pprint

In [2]:
data = [[1, 2.1],[3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data.dtype

torch.float32

In [4]:
np_array = np.array(data, dtype=np.int64)
np_array.dtype

dtype('int64')

In [5]:
x_data_t = torch.from_numpy(np_array)
x_data_t.dtype

torch.int64

In [6]:
x_data_t

tensor([[1, 2],
        [3, 4]])

In [24]:
x_ones = torch.ones_like(x_data_t)#torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")



Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [7]:
x_rand = torch.rand_like(x_data_t, dtype=torch.float32,)
# x_rand

In [8]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.1326, 0.5274],
        [0.4229, 0.3189]]) 



In [9]:
shape = (2,4)
rand = torch.randint_like(x_data_t,10)
print(rand)

tensor([[9, 8],
        [3, 5]])


In [10]:
zeros = torch.zeros(shape)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
ones = torch.ones(shape)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [12]:
ones.data

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
tensor = torch.rand(shape, )
print(tensor)

tensor([[0.8940, 0.5264, 0.2204, 0.9920],
        [0.5395, 0.0264, 0.7710, 0.5671]])


In [14]:
# tensor = torch.rand(shape, )
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.8940, 0.5264, 0.2204, 0.9920])
First column: tensor([0.8940, 0.5395])
Last column: tensor([0.9920, 0.5671])
tensor([[0.8940, 0.0000, 0.2204, 0.9920],
        [0.5395, 0.0000, 0.7710, 0.5671]])


In [15]:
print(f"Last column: {tensor[:, -1]}")

Last column: tensor([0.9920, 0.5671])


In [33]:
t1 = torch.cat([tensor, tensor], dim=1)
print(t1), print(t1.shape)

tensor([[0.8940, 0.0000, 0.2204, 0.9920, 0.8940, 0.0000, 0.2204, 0.9920],
        [0.5395, 0.0000, 0.7710, 0.5671, 0.5395, 0.0000, 0.7710, 0.5671]])
torch.Size([2, 8])


(None, None)

In [23]:
t1 = torch.stack([tensor, tensor], dim=0)
pprint(t1),print(t1.shape)

tensor([[[0.8940, 0.0000, 0.2204, 0.9920],
         [0.5395, 0.0000, 0.7710, 0.5671]],

        [[0.8940, 0.0000, 0.2204, 0.9920],
         [0.5395, 0.0000, 0.7710, 0.5671]]])
torch.Size([2, 2, 4])


(None, None)

In [34]:
t1 = torch.stack([tensor, tensor], dim=1)
pprint(t1),print(t1.shape)

tensor([[[0.8940, 0.0000, 0.2204, 0.9920],
         [0.8940, 0.0000, 0.2204, 0.9920]],

        [[0.5395, 0.0000, 0.7710, 0.5671],
         [0.5395, 0.0000, 0.7710, 0.5671]]])
torch.Size([2, 2, 4])


(None, None)

In [25]:
t1 = torch.stack([tensor, tensor], dim=2)
pprint(t1),print(t1.shape)

tensor([[[0.8940, 0.8940],
         [0.0000, 0.0000],
         [0.2204, 0.2204],
         [0.9920, 0.9920]],

        [[0.5395, 0.5395],
         [0.0000, 0.0000],
         [0.7710, 0.7710],
         [0.5671, 0.5671]]])
torch.Size([2, 4, 2])


(None, None)

In [29]:
t1 = torch.stack([tensor, tensor], dim=-1)
pprint(t1),print(t1.shape)

tensor([[[0.8940, 0.8940],
         [0.0000, 0.0000],
         [0.2204, 0.2204],
         [0.9920, 0.9920]],

        [[0.5395, 0.5395],
         [0.0000, 0.0000],
         [0.7710, 0.7710],
         [0.5671, 0.5671]]])
torch.Size([2, 4, 2])


(None, None)

In [35]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [37]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
print(torch.matmul(tensor, tensor.T, out=y3))


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [47]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 3)
val = torch.matmul(tensor1, tensor2)
val, val.size()

(tensor([[[ 1.2310e+00, -9.7392e-01, -8.9165e-01],
          [-1.8735e+00,  3.2138e+00,  1.2096e-01],
          [-2.8794e+00, -9.7351e-01, -5.0815e-01]],
 
         [[-3.9462e+00, -6.9280e-01,  6.7019e-01],
          [ 2.1365e+00,  3.1491e+00,  2.1282e-01],
          [ 2.4890e+00,  2.2651e+00, -2.9808e-01]],
 
         [[-1.5001e-01,  1.0239e+00, -1.7630e-01],
          [ 5.0638e-01, -2.0322e+00,  3.9017e-01],
          [-4.4194e-01,  5.0083e+00, -4.5330e-02]],
 
         [[-6.0089e-01,  8.3368e-01,  1.5870e-01],
          [ 2.8052e+00,  6.4455e-01, -1.5054e-02],
          [-1.9389e+00, -1.6463e-01,  3.9564e-01]],
 
         [[ 1.3044e+00, -8.0269e+00,  8.9669e-02],
          [-9.1085e-01, -1.3399e+00,  5.3261e-01],
          [ 5.0571e-01, -4.5804e-01,  3.3362e-01]],
 
         [[-6.3756e-01,  4.0915e-01, -1.7228e-01],
          [ 1.5376e+00,  2.0719e+00, -1.3470e-01],
          [-2.0013e+00, -2.1150e+00,  7.7048e-01]],
 
         [[ 6.0902e-03,  2.8891e-01, -6.4738e-01],
          [ 6

In [46]:
tensor1

tensor([[[ 1.9725e-01, -1.0088e+00,  3.2596e-01,  4.4046e-01],
         [-7.9309e-01,  6.2696e-01, -3.1043e-01, -9.1254e-01],
         [ 1.2673e-01,  2.9657e-01, -1.3579e+00,  8.8504e-02]],

        [[-5.0641e-01, -4.3720e-01,  3.6183e-01, -1.4852e-02],
         [ 9.4787e-01,  2.4566e+00, -8.3772e-01, -6.8412e-01],
         [-5.6439e-01, -1.3055e-01,  7.5202e-02, -1.4386e-01]],

        [[ 1.3278e+00, -1.4871e+00, -8.6121e-01, -9.7113e-01],
         [ 1.7892e+00,  1.2806e+00,  4.2999e-01, -2.2527e-01],
         [-8.5567e-01,  5.2439e-01,  1.4869e+00, -7.5298e-05]],

        [[ 9.4410e-01,  2.8592e-01, -1.0301e+00, -4.0030e-01],
         [ 9.7545e-01,  3.0664e-01,  8.7698e-01,  9.7571e-01],
         [-2.8977e-01,  2.1732e+00,  1.0563e-02, -5.9326e-02]],

        [[-5.4166e-01, -9.9466e-02, -1.7062e-01,  5.6098e-01],
         [-1.0757e+00,  1.0069e+00,  4.7415e-01,  6.6102e-01],
         [-1.1215e+00,  3.9868e-01, -4.8302e-01, -1.2813e-01]],

        [[ 1.4544e+00, -1.1112e+00, -1.1015e+

In [56]:
# vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
print("vector x vector")
print(tensor1, tensor2, torch.matmul(tensor1, tensor2), torch.matmul(tensor1, tensor2).size())
print("\n\n\n")


vector x vector
tensor([0.0680, 1.6137, 0.3150]) tensor([-1.3935, -0.1973, -1.0452]) tensor(-0.7423) torch.Size([])






In [70]:
# matrix x vector
tensor1 = torch.ones(3, 4)
tensor2 = torch.ones(4)
torch.matmul(tensor1, tensor2).size()
print("matrix x vector")
print(tensor1, tensor2,  torch.matmul(tensor1, tensor2), torch.matmul(tensor1, tensor2).size())
print(tensor1.shape, tensor2.shape, torch.matmul(tensor1, tensor2).shape)
print("\n\n\n")



matrix x vector
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) tensor([1., 1., 1., 1.]) tensor([4., 4., 4.]) torch.Size([3])
torch.Size([3, 4]) torch.Size([4]) torch.Size([3])






In [67]:
tensor2.reshape(1, -1).T

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [72]:
# batched matrix x broadcasted vector
tensor1 = torch.ones(10, 3, 4)
tensor2 = torch.ones(4)
torch.matmul(tensor1, tensor2).size()
print("batched matrix x broadcasted vector")
print(tensor1, tensor2,  torch.matmul(tensor1, tensor2), torch.matmul(tensor1, tensor2).size())
print(tensor1.shape, tensor2.shape, torch.matmul(tensor1, tensor2).shape)

print("\n\n\n")



batched matrix x broadcasted vector
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) tensor([1., 1., 1., 1.]) tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],

In [88]:
# batched matrix x batched matrix
tensor1 = torch.ones(10, 3, 4)
tensor2 = torch.ones(1, 4, 5)
torch.matmul(tensor1, tensor2).size()
print("batched matrix x batched matrix")
# print("batched matrix", tensor1)
# print("batched matrix", tensor2)
# print(tensor1, tensor2,  torch.matmul(tensor1, tensor2), torch.matmul(tensor1, tensor2).size())

print(torch.matmul(tensor1, tensor2).shape)
print("\n\n\n")



batched matrix x batched matrix
torch.Size([10, 3, 5])






In [123]:
# batched matrix x broadcasted matrix
tensor1 = torch.ones(10, 3, 4)
tensor2 = torch.randn(1, 4, 4)
torch.matmul(tensor1, tensor2).size()
print("batched matrix x broadcasted matrix")
# print("batched matrix", tensor1)
# print("batched matrix", tensor2)
# print(torch.matmul(tensor1, tensor2))

# print(torch.matmul(tensor1, tensor2).shape)
# print(tensor1, tensor2, torch.matmul(tensor1, tensor2).size())


batched matrix x broadcasted matrix


In [107]:
# tensor1.mul(tensor2)

In [112]:
# torch.mul(tensor1, tensor2, out=torch.rand_like(torch.ones((3,3)))).shape

/tmp/ipykernel_13581/4191249036.py:1: UserWarning: An output with one or more elements was resized since it had shape [3, 3], which does not match the required output shape [10, 3, 4]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  torch.mul(tensor1, tensor2, out=torch.rand_like(torch.ones((3,3)))).shape


torch.Size([10, 3, 4])

In [133]:
tensor2 = torch.randn(1, 5, 4)
tensor2.reshape(-1,)

tensor([-0.5556,  0.7006, -0.6526, -0.6878,  2.1820, -1.6005,  0.3764,  2.0375,
        -0.7816, -0.3262,  0.6575,  0.3219, -1.0887,  1.2436, -1.0134,  0.9748,
         0.0273, -0.0653,  1.4627, -0.3439])

In [137]:
tensor2.tril_()

tensor([[[-0.5556,  0.0000,  0.0000,  0.0000],
         [ 2.1820, -1.6005,  0.0000,  0.0000],
         [-0.7816, -0.3262,  0.6575,  0.0000],
         [-1.0887,  1.2436, -1.0134,  0.9748],
         [ 0.0273, -0.0653,  1.4627, -0.3439]]])

In [139]:
tensor2 = torch.randn(1, 5, 4)
tensor2.triu()

tensor([[[-0.0840, -0.2536, -0.3968,  1.2024],
         [ 0.0000, -0.4550,  1.1030, -0.6016],
         [ 0.0000,  0.0000, -0.2846,  0.2429],
         [ 0.0000,  0.0000,  0.0000, -1.2177],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]])

In [149]:
x = torch.rand(2, 2, 3, 5)
print(x, x.size())
x.reshape(-1,)


tensor([[[[0.1762, 0.1118, 0.9870, 0.8794, 0.3210],
          [0.7764, 0.7793, 0.6499, 0.7619, 0.2812],
          [0.9136, 0.9086, 0.5870, 0.2981, 0.9414]],

         [[0.1538, 0.4206, 0.5065, 0.6086, 0.3189],
          [0.4396, 0.3494, 0.2459, 0.9426, 0.6564],
          [0.9051, 0.7212, 0.6568, 0.9289, 0.1827]]],


        [[[0.5102, 0.3080, 0.2807, 0.6196, 0.7402],
          [0.0363, 0.5396, 0.1127, 0.3150, 0.9541],
          [0.4628, 0.5697, 0.4793, 0.4545, 0.0991]],

         [[0.8577, 0.1877, 0.1338, 0.5869, 0.5915],
          [0.2536, 0.1757, 0.7289, 0.8487, 0.9442],
          [0.5395, 0.8611, 0.2982, 0.2728, 0.6216]]]]) torch.Size([2, 2, 3, 5])


tensor([0.1762, 0.1118, 0.9870, 0.8794, 0.3210, 0.7764, 0.7793, 0.6499, 0.7619,
        0.2812, 0.9136, 0.9086, 0.5870, 0.2981, 0.9414, 0.1538, 0.4206, 0.5065,
        0.6086, 0.3189, 0.4396, 0.3494, 0.2459, 0.9426, 0.6564, 0.9051, 0.7212,
        0.6568, 0.9289, 0.1827, 0.5102, 0.3080, 0.2807, 0.6196, 0.7402, 0.0363,
        0.5396, 0.1127, 0.3150, 0.9541, 0.4628, 0.5697, 0.4793, 0.4545, 0.0991,
        0.8577, 0.1877, 0.1338, 0.5869, 0.5915, 0.2536, 0.1757, 0.7289, 0.8487,
        0.9442, 0.5395, 0.8611, 0.2982, 0.2728, 0.6216])

In [151]:
torch.permute(x, (3, 2, 1, 0))

tensor([[[[0.1762, 0.5102],
          [0.1538, 0.8577]],

         [[0.7764, 0.0363],
          [0.4396, 0.2536]],

         [[0.9136, 0.4628],
          [0.9051, 0.5395]]],


        [[[0.1118, 0.3080],
          [0.4206, 0.1877]],

         [[0.7793, 0.5396],
          [0.3494, 0.1757]],

         [[0.9086, 0.5697],
          [0.7212, 0.8611]]],


        [[[0.9870, 0.2807],
          [0.5065, 0.1338]],

         [[0.6499, 0.1127],
          [0.2459, 0.7289]],

         [[0.5870, 0.4793],
          [0.6568, 0.2982]]],


        [[[0.8794, 0.6196],
          [0.6086, 0.5869]],

         [[0.7619, 0.3150],
          [0.9426, 0.8487]],

         [[0.2981, 0.4545],
          [0.9289, 0.2728]]],


        [[[0.3210, 0.7402],
          [0.3189, 0.5915]],

         [[0.2812, 0.9541],
          [0.6564, 0.9442]],

         [[0.9414, 0.0991],
          [0.1827, 0.6216]]]])